import { MongoClient } from 'mongodb';
import { hashPassword } from '../utils/auth';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config({ path: '.env.local' });

const mongoUrl =
  process.env.DATABASE_URL || 'mongodb://localhost:27017/mutual_funds_db';

async function main() {
  console.log('Starting database seed with MongoDB...');
  console.log('Connecting to:', mongoUrl);

  const client = new MongoClient(mongoUrl);

  try {
    await client.connect();
    console.log('✓ Connected to MongoDB');

    const db = client.db();

    // Create admin user
    const adminPassword = await hashPassword('admin123');
    const usersCollection = db.collection('users');

    const existingAdmin = await usersCollection.findOne({
      email: 'admin@mutualfunds.com',
    });

    if (!existingAdmin) {
      await usersCollection.insertOne({
        email: 'admin@mutualfunds.com',
        password: adminPassword,
        name: 'Admin User',
        role: 'ADMIN',
        isVerified: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      console.log(
        '✓ Admin user created: admin@mutualfunds.com (password: admin123)'
      );
    } else {
      console.log('✓ Admin user already exists: admin@mutualfunds.com');
    }

    // Create sample test user
    const testUserPassword = await hashPassword('test123');
    const existingTestUser = await usersCollection.findOne({
      email: 'test@example.com',
    });

    if (!existingTestUser) {
      await usersCollection.insertOne({
        email: 'test@example.com',
        password: testUserPassword,
        name: 'Test User',
        role: 'USER',
        isVerified: true,
        age: 30,
        riskLevel: 'MEDIUM',
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      console.log('✓ Test user created: test@example.com (password: test123)');
    } else {
      console.log('✓ Test user already exists: test@example.com');
    }

    // Create sample funds
    const fundsCollection = db.collection('funds');

    const funds = [
      {
        amfiCode: 'HDFC001',
        name: 'HDFC Top 100 Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 1.25,
        description: 'Large cap equity fund investing in top 100 companies',
        inceptionDate: new Date('2010-01-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI001',
        name: 'ICICI Prudential Value Discovery Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.85,
        description: 'Mid cap value focused equity fund',
        inceptionDate: new Date('2012-06-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI001',
        name: 'SBI Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 2.15,
        description: 'Small cap growth focused equity fund',
        inceptionDate: new Date('2015-03-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'AXIS001',
        name: 'Axis Bluechip Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.65,
        description:
          'Flagship large cap fund focusing on quality bluechip stocks',
        inceptionDate: new Date('2008-12-29'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MIRAE001',
        name: 'Mirae Asset Emerging Bluechip Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.85,
        description: 'Mid cap fund investing in emerging quality businesses',
        inceptionDate: new Date('2013-07-03'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'KOTAK001',
        name: 'Kotak Standard Multicap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.75,
        description:
          'Multi cap fund with flexible allocation across market caps',
        inceptionDate: new Date('2011-04-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI002',
        name: 'SBI Bluechip Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.7,
        description:
          'Large cap fund investing in established bluechip companies',
        inceptionDate: new Date('2006-02-14'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HDFC002',
        name: 'HDFC Mid-Cap Opportunities Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.15,
        description: 'Mid cap fund focusing on growth opportunities',
        inceptionDate: new Date('2007-06-28'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Additional Large Cap Funds
      {
        amfiCode: 'ICICI002',
        name: 'ICICI Prudential Bluechip Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.85,
        description: 'Large cap fund investing in quality bluechip stocks',
        inceptionDate: new Date('2008-05-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'AXIS002',
        name: 'Axis Focused 25 Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        expenseRatio: 0.55,
        description: 'Concentrated large cap portfolio of 25 quality stocks',
        inceptionDate: new Date('2013-01-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PARAG001',
        name: 'Parag Parikh Flexi Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.68,
        description: 'Large cap focused flexi cap fund with global exposure',
        inceptionDate: new Date('2013-05-28'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANK001',
        name: 'Franklin India Bluechip Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.72,
        description:
          'Well-established large cap fund with consistent track record',
        inceptionDate: new Date('2011-11-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Additional Mid Cap Funds
      {
        amfiCode: 'AXIS003',
        name: 'Axis Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.58,
        description: 'Mid cap fund with focus on quality and growth',
        inceptionDate: new Date('2011-03-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'KOTAK002',
        name: 'Kotak Emerging Equity Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 0.95,
        description: 'Mid cap fund identifying emerging market leaders',
        inceptionDate: new Date('2007-03-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANK002',
        name: 'Franklin India Prima Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.05,
        description: 'Mid cap fund with consistent alpha generation',
        inceptionDate: new Date('1993-12-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'DSP001',
        name: 'DSP Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.88,
        description: 'Mid cap fund with bottom-up stock selection approach',
        inceptionDate: new Date('2006-11-07'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Additional Small Cap Funds
      {
        amfiCode: 'AXIS004',
        name: 'Axis Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 0.65,
        description: 'Small cap fund focusing on high growth potential stocks',
        inceptionDate: new Date('2013-09-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'KOTAK003',
        name: 'Kotak Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.25,
        description: 'Small cap fund with focus on emerging businesses',
        inceptionDate: new Date('2005-02-24'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON001',
        name: 'Nippon India Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.15,
        description: 'Small cap fund with strong research-driven approach',
        inceptionDate: new Date('2010-09-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HDFC003',
        name: 'HDFC Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.18,
        description: 'Small cap fund with proven track record',
        inceptionDate: new Date('2008-04-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI003',
        name: 'SBI Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.32,
        description: 'Small cap fund for aggressive growth investors',
        inceptionDate: new Date('2009-09-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Commodity & Gold ETFs
      {
        amfiCode: 'GOLD001',
        name: 'SBI Gold ETF',
        type: 'Commodity',
        category: 'GOLD_ETF',
        subCategory: 'Gold',
        fundHouse: 'SBI Mutual Fund',
        nav: 58.42,
        aum: 1250,
        returns: {
          '1Y': 12.5,
          '3Y': 15.8,
          '5Y': 11.2,
        },
        riskLevel: 'Moderate',
        minInvestment: 100,
        exitLoad: 0,
        benchmark: 'Gold Price Index',
        expenseRatio: 0.5,
        description: 'Gold ETF tracking domestic gold prices',
        inceptionDate: new Date('2009-05-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'GOLD002',
        name: 'HDFC Gold ETF',
        type: 'Commodity',
        category: 'GOLD_ETF',
        subCategory: 'Gold',
        fundHouse: 'HDFC Mutual Fund',
        nav: 55.78,
        aum: 980,
        returns: {
          '1Y': 12.3,
          '3Y': 15.5,
          '5Y': 11.0,
        },
        riskLevel: 'Moderate',
        minInvestment: 100,
        exitLoad: 0,
        benchmark: 'Gold Price Index',
        expenseRatio: 0.55,
        description: 'ETF providing exposure to physical gold',
        inceptionDate: new Date('2010-01-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'GOLD003',
        name: 'Nippon India Gold ETF',
        type: 'Commodity',
        category: 'GOLD_ETF',
        subCategory: 'Gold',
        fundHouse: 'Nippon India Mutual Fund',
        nav: 56.92,
        aum: 750,
        returns: {
          '1Y': 12.8,
          '3Y': 16.1,
          '5Y': 11.5,
        },
        riskLevel: 'Moderate',
        minInvestment: 100,
        exitLoad: 0,
        benchmark: 'Gold Price Index',
        expenseRatio: 0.52,
        description: 'Gold ETF for portfolio diversification',
        inceptionDate: new Date('2011-03-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SILV001',
        name: 'Axis Silver ETF',
        type: 'Commodity',
        category: 'SILVER_ETF',
        subCategory: 'Silver',
        fundHouse: 'Axis Mutual Fund',
        nav: 72.15,
        aum: 420,
        returns: {
          '1Y': 8.5,
          '3Y': 12.3,
          '5Y': 9.8,
        },
        riskLevel: 'Moderate to High',
        minInvestment: 100,
        exitLoad: 0,
        benchmark: 'Silver Price Index',
        expenseRatio: 0.65,
        description: 'Silver ETF tracking domestic silver prices',
        inceptionDate: new Date('2017-06-22'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'COMM001',
        name: 'ICICI Prudential Commodities Fund',
        type: 'Commodity',
        category: 'COMMODITY',
        subCategory: 'Multi-Commodity',
        fundHouse: 'ICICI Prudential Mutual Fund',
        nav: 18.65,
        aum: 350,
        returns: {
          '1Y': 7.2,
          '3Y': 10.5,
          '5Y': 8.9,
        },
        riskLevel: 'Moderate to High',
        minInvestment: 5000,
        exitLoad: 0.5,
        benchmark: 'Multi-Commodity Index',
        expenseRatio: 1.15,
        description: 'Fund investing in commodity-based securities',
        inceptionDate: new Date('2020-08-12'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== ADDITIONAL LARGE CAP FUNDS ==========
      {
        amfiCode: 'UTI001',
        name: 'UTI Nifty 50 Index Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.18,
        description: 'Low-cost passive index fund tracking Nifty 50',
        inceptionDate: new Date('2000-01-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'IDFC001',
        name: 'IDFC Focused Equity Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.92,
        description: 'Concentrated large cap portfolio of 25-30 stocks',
        inceptionDate: new Date('2013-12-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'LIC001',
        name: 'LIC MF Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.88,
        description: 'Large cap fund from LIC Mutual Fund',
        inceptionDate: new Date('2011-05-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'TATA001',
        name: 'Tata Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.75,
        description: 'Diversified large cap fund from Tata Mutual Fund',
        inceptionDate: new Date('2012-03-22'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'CANARA001',
        name: 'Canara Robeco Bluechip Equity Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.82,
        description: 'Large cap fund with focus on quality companies',
        inceptionDate: new Date('2010-07-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== MORE MID CAP FUNDS ==========
      {
        amfiCode: 'SUNDARAM001',
        name: 'Sundaram Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.05,
        description: 'Mid cap fund with value investing approach',
        inceptionDate: new Date('2009-05-18'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'INVESCO001',
        name: 'Invesco India Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 0.98,
        description: 'Mid cap fund with growth-oriented strategy',
        inceptionDate: new Date('2007-10-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'QUANT001',
        name: 'Quant Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.72,
        description: 'Quantitative approach to mid cap investing',
        inceptionDate: new Date('2014-03-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MAHINDRA001',
        name: 'Mahindra Manulife Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.12,
        description: 'Mid cap fund identifying future leaders',
        inceptionDate: new Date('2015-06-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PGIM001',
        name: 'PGIM India Midcap Opportunities Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.95,
        description: 'Mid cap fund with opportunistic approach',
        inceptionDate: new Date('2011-08-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== MORE SMALL CAP FUNDS ==========
      {
        amfiCode: 'FRANK003',
        name: 'Franklin India Smaller Companies Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.28,
        description: 'Small cap fund with long-term value creation focus',
        inceptionDate: new Date('1998-06-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'DSP002',
        name: 'DSP Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.18,
        description: 'Small cap fund with proven track record',
        inceptionDate: new Date('2007-09-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'QUANT002',
        name: 'Quant Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 0.85,
        description: 'Data-driven small cap investing',
        inceptionDate: new Date('2013-11-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'TATA002',
        name: 'Tata Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.35,
        description: 'Small cap fund for high growth potential',
        inceptionDate: new Date('2013-01-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'LIC002',
        name: 'LIC MF Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.42,
        description: 'Small cap fund with aggressive growth strategy',
        inceptionDate: new Date('2014-02-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== FLEXI CAP / MULTI CAP FUNDS ==========
      {
        amfiCode: 'MIRAE002',
        name: 'Mirae Asset Flexi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.92,
        description: 'Flexible allocation across market capitalizations',
        inceptionDate: new Date('2019-11-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'CANARA002',
        name: 'Canara Robeco Flexi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.88,
        description: 'Multi cap fund with flexible mandate',
        inceptionDate: new Date('2003-05-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'UTI002',
        name: 'UTI Flexi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.95,
        description: 'Diversified multi cap fund from UTI',
        inceptionDate: new Date('2005-11-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'JM001',
        name: 'JM Flexi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 1.12,
        description: 'Multi cap fund with dynamic allocation',
        inceptionDate: new Date('2008-08-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BOI001',
        name: 'BOI AXA Multi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 1.05,
        description: 'Multi cap fund from BOI AXA Mutual Fund',
        inceptionDate: new Date('2012-06-18'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== SECTORAL / THEMATIC FUNDS ==========
      {
        amfiCode: 'ICICI003',
        name: 'ICICI Prudential Technology Fund',
        type: 'EQUITY',
        category: 'SECTORAL',
        benchmark: 'Nifty IT Index',
        expenseRatio: 1.15,
        description: 'Sectoral fund investing in IT and technology stocks',
        inceptionDate: new Date('2000-03-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI004',
        name: 'SBI Banking & Financial Services Fund',
        type: 'EQUITY',
        category: 'SECTORAL',
        benchmark: 'Nifty Bank Index',
        expenseRatio: 1.25,
        description: 'Sectoral fund focused on banking and financial stocks',
        inceptionDate: new Date('2015-07-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON002',
        name: 'Nippon India Pharma Fund',
        type: 'EQUITY',
        category: 'SECTORAL',
        benchmark: 'Nifty Pharma Index',
        expenseRatio: 1.35,
        description: 'Pharma-focused sectoral fund',
        inceptionDate: new Date('2004-04-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'AXIS005',
        name: 'Axis ESG Equity Fund',
        type: 'EQUITY',
        category: 'THEMATIC',
        benchmark: 'Nifty 100',
        expenseRatio: 0.78,
        description: 'ESG-focused thematic fund',
        inceptionDate: new Date('2020-12-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SUNDARAM002',
        name: 'Sundaram Rural India Fund',
        type: 'EQUITY',
        category: 'THEMATIC',
        benchmark: 'Nifty 500',
        expenseRatio: 1.28,
        description: 'Thematic fund investing in rural consumption theme',
        inceptionDate: new Date('2010-12-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANKLIN004',
        name: 'Franklin Build India Fund',
        type: 'EQUITY',
        category: 'THEMATIC',
        benchmark: 'Nifty 500',
        expenseRatio: 1.18,
        description: 'Infrastructure and construction themed fund',
        inceptionDate: new Date('2009-05-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== DEBT FUNDS ==========
      {
        amfiCode: 'HDFC004',
        name: 'HDFC Short Term Debt Fund',
        type: 'DEBT',
        category: 'DEBT',
        benchmark: 'CRISIL Short Term Debt Index',
        expenseRatio: 0.45,
        description: 'Short duration debt fund for conservative investors',
        inceptionDate: new Date('2010-06-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI004',
        name: 'ICICI Prudential Corporate Bond Fund',
        type: 'DEBT',
        category: 'DEBT',
        benchmark: 'CRISIL Corporate Bond Index',
        expenseRatio: 0.38,
        description: 'Corporate bond fund with high credit quality',
        inceptionDate: new Date('2009-11-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'AXIS006',
        name: 'Axis Banking & PSU Debt Fund',
        type: 'DEBT',
        category: 'DEBT',
        benchmark: 'CRISIL Banking & PSU Debt Index',
        expenseRatio: 0.28,
        description: 'Debt fund investing in bank and PSU bonds',
        inceptionDate: new Date('2013-04-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI005',
        name: 'SBI Magnum Gilt Fund',
        type: 'DEBT',
        category: 'DEBT',
        benchmark: 'CRISIL 10 Year Gilt Index',
        expenseRatio: 0.52,
        description: 'Government securities fund',
        inceptionDate: new Date('1999-07-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'KOTAK004',
        name: 'Kotak Low Duration Fund',
        type: 'DEBT',
        category: 'DEBT',
        benchmark: 'CRISIL Low Duration Debt Index',
        expenseRatio: 0.42,
        description: 'Low duration debt fund for short-term goals',
        inceptionDate: new Date('2011-09-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANKLIN005',
        name: 'Franklin India Ultra Short Bond Fund',
        type: 'DEBT',
        category: 'DEBT',
        benchmark: 'CRISIL Ultra Short Term Debt Index',
        expenseRatio: 0.35,
        description: 'Ultra-short duration debt fund',
        inceptionDate: new Date('2003-05-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== HYBRID FUNDS ==========
      {
        amfiCode: 'HDFC005',
        name: 'HDFC Balanced Advantage Fund',
        type: 'HYBRID',
        category: 'HYBRID',
        benchmark: 'CRISIL Hybrid 35+65 Index',
        expenseRatio: 0.92,
        description: 'Dynamic asset allocation hybrid fund',
        inceptionDate: new Date('2000-01-03'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI005',
        name: 'ICICI Prudential Equity & Debt Fund',
        type: 'HYBRID',
        category: 'HYBRID',
        benchmark: 'CRISIL Hybrid 35+65 Index',
        expenseRatio: 1.05,
        description: 'Aggressive hybrid fund with equity focus',
        inceptionDate: new Date('1999-11-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI006',
        name: 'SBI Equity Hybrid Fund',
        type: 'HYBRID',
        category: 'HYBRID',
        benchmark: 'CRISIL Hybrid 35+65 Index',
        expenseRatio: 0.88,
        description: 'Balanced hybrid fund for moderate risk investors',
        inceptionDate: new Date('1995-01-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'KOTAK005',
        name: 'Kotak Multi Asset Allocator Fund',
        type: 'HYBRID',
        category: 'HYBRID',
        benchmark: 'CRISIL Hybrid 35+65 Index',
        expenseRatio: 0.95,
        description: 'Multi-asset fund with gold exposure',
        inceptionDate: new Date('2015-03-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MIRAE003',
        name: 'Mirae Asset Hybrid Equity Fund',
        type: 'HYBRID',
        category: 'HYBRID',
        benchmark: 'CRISIL Hybrid 35+65 Index',
        expenseRatio: 0.78,
        description: 'Aggressive hybrid fund with balanced approach',
        inceptionDate: new Date('2017-07-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== INDEX FUNDS ==========
      {
        amfiCode: 'UTI003',
        name: 'UTI Nifty Next 50 Index Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty Next 50',
        expenseRatio: 0.22,
        description: 'Index fund tracking Nifty Next 50',
        inceptionDate: new Date('2017-02-06'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI006',
        name: 'ICICI Prudential Nifty 100 Index Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.25,
        description: 'Passive fund tracking top 100 companies',
        inceptionDate: new Date('2020-01-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HDFC006',
        name: 'HDFC Index Fund - Sensex Plan',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'BSE Sensex',
        expenseRatio: 0.2,
        description: 'Index fund tracking BSE Sensex',
        inceptionDate: new Date('2002-12-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'AXIS007',
        name: 'Axis Nifty 50 Index Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.12,
        description: 'Ultra-low cost Nifty 50 index fund',
        inceptionDate: new Date('2020-10-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON003',
        name: 'Nippon India Index Fund - Nifty Midcap 150',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.35,
        description: 'Midcap index fund for passive investors',
        inceptionDate: new Date('2019-06-12'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== ELSS (TAX SAVER) FUNDS ==========
      {
        amfiCode: 'AXIS008',
        name: 'Axis Long Term Equity Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'Nifty 500',
        expenseRatio: 0.68,
        description: 'ELSS tax saver fund with 3-year lock-in',
        inceptionDate: new Date('2009-12-29'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MIRAE004',
        name: 'Mirae Asset Tax Saver Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'Nifty 500',
        expenseRatio: 0.55,
        description: 'Tax saving ELSS fund with strong performance',
        inceptionDate: new Date('2015-12-28'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI007',
        name: 'ICICI Prudential Long Term Equity Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'Nifty 500',
        expenseRatio: 0.92,
        description: 'Popular ELSS fund for tax saving under 80C',
        inceptionDate: new Date('1999-10-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI007',
        name: 'SBI Long Term Equity Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'BSE 200',
        expenseRatio: 0.85,
        description: 'Tax saver ELSS fund from SBI',
        inceptionDate: new Date('1993-03-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'DSP003',
        name: 'DSP Tax Saver Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'Nifty 500',
        expenseRatio: 0.88,
        description: 'ELSS fund with consistent long-term returns',
        inceptionDate: new Date('2007-01-17'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== MORE COMMODITY FUNDS ==========
      {
        amfiCode: 'QUANTUM001',
        name: 'Quantum Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.77,
        description: 'Gold savings fund for long-term investors',
        inceptionDate: new Date('2008-02-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'KOTAK006',
        name: 'Kotak Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.95,
        description: 'Gold fund providing commodity diversification',
        inceptionDate: new Date('2011-11-28'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'AXIS009',
        name: 'Axis Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.62,
        description: 'Gold fund for portfolio hedging',
        inceptionDate: new Date('2016-04-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== ADDITIONAL 20+ COMMODITY FUNDS ==========
      {
        amfiCode: 'ICICI010',
        name: 'ICICI Prudential Gold ETF FoF',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.72,
        description:
          'Gold fund-of-funds, 5Y CAGR: 11.8%, tracks physical gold prices',
        inceptionDate: new Date('2011-09-27'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ADITYA005',
        name: 'Aditya Birla Sun Life Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.88,
        description: 'Gold fund with 3Y CAGR: 16.2%, excellent liquidity',
        inceptionDate: new Date('2011-10-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'UTI004',
        name: 'UTI Gold ETF',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.58,
        description: 'Low-cost gold ETF, 5Y CAGR: 11.5%, high AUM ₹2,500 Cr',
        inceptionDate: new Date('2007-03-16'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'IDFC002',
        name: 'IDFC Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.68,
        description: 'Gold fund for hedging, 3Y CAGR: 15.8%',
        inceptionDate: new Date('2010-10-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MOTILAL004',
        name: 'Motilal Oswal Gold & Silver ETFs FoF',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.82,
        description: 'Multi-metal commodity fund, 3Y CAGR: 14.5%',
        inceptionDate: new Date('2020-09-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HSBC005',
        name: 'HSBC Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.75,
        description: 'Gold fund with diversification, 5Y CAGR: 11.2%',
        inceptionDate: new Date('2012-08-08'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'DSP004',
        name: 'DSP Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.69,
        description: 'Gold investment with steady returns, 3Y CAGR: 16.5%',
        inceptionDate: new Date('2008-01-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'INVESCO002',
        name: 'Invesco India Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.85,
        description: 'Gold fund for portfolio protection, 5Y CAGR: 10.8%',
        inceptionDate: new Date('2011-05-13'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'EDELWEISS008',
        name: 'Edelweiss Gold & Silver ETF FoF',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.92,
        description: 'Precious metals fund, 3Y CAGR: 13.8%',
        inceptionDate: new Date('2019-01-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BANDHAN007',
        name: 'Bandhan Gold ETF',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.48,
        description: 'Ultra-low cost gold ETF, tracks domestic gold perfectly',
        inceptionDate: new Date('2020-06-22'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'LIC003',
        name: 'LIC MF Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.95,
        description: 'Gold fund from LIC, 3Y CAGR: 15.2%',
        inceptionDate: new Date('2013-12-16'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'TATA003',
        name: 'Tata Gold Fund',
        type: 'Commodity',
        category: 'GOLD_ETF',
        expenseRatio: 0.78,
        description: 'Gold fund with consistent tracking, 5Y CAGR: 11.3%',
        inceptionDate: new Date('2011-11-02'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Silver ETFs
      {
        amfiCode: 'ICICI011',
        name: 'ICICI Prudential Silver ETF',
        type: 'Commodity',
        category: 'SILVER_ETF',
        expenseRatio: 0.72,
        description: 'Silver ETF tracking domestic prices, 5Y CAGR: 9.5%',
        inceptionDate: new Date('2018-10-12'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI010',
        name: 'SBI Silver ETF',
        type: 'Commodity',
        category: 'SILVER_ETF',
        expenseRatio: 0.68,
        description: 'Silver investment fund, 3Y CAGR: 12.8%',
        inceptionDate: new Date('2019-03-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON006',
        name: 'Nippon India Silver ETF',
        type: 'Commodity',
        category: 'SILVER_ETF',
        expenseRatio: 0.75,
        description: 'Silver ETF with high liquidity, 3Y CAGR: 11.5%',
        inceptionDate: new Date('2018-06-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ADITYA006',
        name: 'Aditya Birla Sun Life Silver ETF',
        type: 'Commodity',
        category: 'SILVER_ETF',
        expenseRatio: 0.82,
        description: 'Silver fund for diversification, 5Y CAGR: 10.2%',
        inceptionDate: new Date('2017-09-28'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Multi-Commodity Funds
      {
        amfiCode: 'AXIS010',
        name: 'Axis Commodity Fund',
        type: 'Commodity',
        category: 'COMMODITY',
        expenseRatio: 1.25,
        description: 'Multi-commodity exposure, 3Y CAGR: 10.5%',
        inceptionDate: new Date('2021-02-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HDFC007',
        name: 'HDFC Commodity Fund',
        type: 'Commodity',
        category: 'COMMODITY',
        expenseRatio: 1.18,
        description: 'Diversified commodity basket, 3Y CAGR: 9.8%',
        inceptionDate: new Date('2020-11-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI011',
        name: 'SBI Magnum Commodities Fund',
        type: 'Commodity',
        category: 'COMMODITY',
        expenseRatio: 1.32,
        description: 'Multi-commodity investment, 5Y CAGR: 8.5%',
        inceptionDate: new Date('2019-01-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON007',
        name: 'Nippon India Commodity Fund',
        type: 'Commodity',
        category: 'COMMODITY',
        expenseRatio: 1.28,
        description: 'Commodity diversification fund, 3Y CAGR: 11.2%',
        inceptionDate: new Date('2020-08-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'QUANT003',
        name: 'Quant Commodity Fund',
        type: 'Commodity',
        category: 'COMMODITY',
        expenseRatio: 0.98,
        description: 'Quantitative commodity strategy, 3Y CAGR: 12.5%',
        inceptionDate: new Date('2021-06-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== INTERNATIONAL FUNDS ==========
      {
        amfiCode: 'FRANK006',
        name: 'Franklin India Feeder - Franklin US Opportunities Fund',
        type: 'EQUITY',
        category: 'INTERNATIONAL',
        benchmark: 'S&P 500',
        expenseRatio: 1.42,
        description: 'International fund investing in US equities',
        inceptionDate: new Date('2012-10-29'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI008',
        name: 'ICICI Prudential US Bluechip Equity Fund',
        type: 'EQUITY',
        category: 'INTERNATIONAL',
        benchmark: 'S&P 500',
        expenseRatio: 1.35,
        description: 'Fund investing in US large-cap stocks',
        inceptionDate: new Date('2012-09-03'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON004',
        name: 'Nippon India Japan Equity Fund',
        type: 'EQUITY',
        category: 'INTERNATIONAL',
        benchmark: 'TOPIX Index',
        expenseRatio: 1.58,
        description: 'Fund providing exposure to Japanese equity market',
        inceptionDate: new Date('2013-03-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MOTILAL001',
        name: 'Motilal Oswal NASDAQ 100 Fund',
        type: 'EQUITY',
        category: 'INTERNATIONAL',
        benchmark: 'NASDAQ 100',
        expenseRatio: 0.65,
        description: 'Tech-focused fund tracking NASDAQ 100',
        inceptionDate: new Date('2020-10-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== ADDITIONAL 50+ EQUITY FUNDS WITH PERFORMANCE DATA ==========
      // More Large Cap Funds
      {
        amfiCode: 'BANDHAN001',
        name: 'Bandhan Core Equity Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.68,
        description:
          'Large cap fund with focus on quality stocks, 3Y CAGR: 14.2%',
        inceptionDate: new Date('2013-09-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'EDELWEISS001',
        name: 'Edelweiss Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.95,
        description: 'Large cap fund from Edelweiss, 5Y CAGR: 12.8%',
        inceptionDate: new Date('2011-06-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HSBC001',
        name: 'HSBC Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.82,
        description: 'Quality large cap fund, consistent 13% CAGR over 5 years',
        inceptionDate: new Date('2009-03-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ADITYA001',
        name: 'Aditya Birla Sun Life Frontline Equity Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.88,
        description: 'Top-tier large cap fund, 10Y CAGR: 13.5%',
        inceptionDate: new Date('2002-08-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BARODA001',
        name: 'Baroda BNP Paribas Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.92,
        description: 'Diversified large cap portfolio, 3Y CAGR: 13.8%',
        inceptionDate: new Date('2012-04-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PRINCIPAL001',
        name: 'Principal Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.78,
        description: 'Large cap fund with steady growth, 5Y CAGR: 12.3%',
        inceptionDate: new Date('2014-01-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // More Mid Cap Funds
      {
        amfiCode: 'EDELWEISS002',
        name: 'Edelweiss Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.15,
        description: 'High-performing mid cap fund, 5Y CAGR: 18.5%',
        inceptionDate: new Date('2008-12-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BANDHAN002',
        name: 'Bandhan Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 0.92,
        description: 'Growth-oriented mid cap fund, 3Y CAGR: 20.2%',
        inceptionDate: new Date('2013-05-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HSBC002',
        name: 'HSBC Midcap Equity Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.08,
        description: 'Mid cap fund with alpha generation, 5Y CAGR: 17.8%',
        inceptionDate: new Date('2004-12-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MOTILAL002',
        name: 'Motilal Oswal Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.72,
        description: 'Research-driven mid cap fund, 3Y CAGR: 19.5%',
        inceptionDate: new Date('2014-02-18'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'L&T001',
        name: 'L&T Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 0.98,
        description: 'Quality mid cap fund, consistent 18% returns',
        inceptionDate: new Date('2004-06-24'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SHRIRAM001',
        name: 'Shriram Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.22,
        description: 'Dynamic mid cap investing, 5Y CAGR: 17.2%',
        inceptionDate: new Date('2015-08-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // More Small Cap Funds
      {
        amfiCode: 'BANDHAN003',
        name: 'Bandhan Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.35,
        description: 'Aggressive small cap fund, 5Y CAGR: 24.5%',
        inceptionDate: new Date('2013-03-12'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'EDELWEISS003',
        name: 'Edelweiss Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.42,
        description: 'High-growth small cap fund, 3Y CAGR: 26.8%',
        inceptionDate: new Date('2012-11-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'L&T002',
        name: 'L&T Emerging Businesses Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.28,
        description: 'Small cap fund for future leaders, 5Y CAGR: 23.2%',
        inceptionDate: new Date('2005-01-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'UNION001',
        name: 'Union Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.48,
        description: 'Small cap fund with strong performance, 3Y CAGR: 25.5%',
        inceptionDate: new Date('2014-09-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HSBC003',
        name: 'HSBC Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.38,
        description: 'Small cap fund with quality focus, 5Y CAGR: 22.8%',
        inceptionDate: new Date('2005-05-09'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ADITYA002',
        name: 'Aditya Birla Sun Life Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.32,
        description: 'Well-researched small cap portfolio, 10Y CAGR: 21.5%',
        inceptionDate: new Date('2002-09-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // More Flexi/Multi Cap Funds
      {
        amfiCode: 'EDELWEISS004',
        name: 'Edelweiss Flexi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.85,
        description: 'Flexible multi cap allocation, 5Y CAGR: 15.8%',
        inceptionDate: new Date('2010-08-25'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BANDHAN004',
        name: 'Bandhan Flexi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.78,
        description: 'Dynamic multi cap strategy, 3Y CAGR: 16.5%',
        inceptionDate: new Date('2013-01-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PRINCIPAL002',
        name: 'Principal Multi Cap Growth Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 1.05,
        description: 'Growth-focused multi cap fund, 5Y CAGR: 14.8%',
        inceptionDate: new Date('2011-12-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BARODA002',
        name: 'Baroda BNP Paribas Multi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.95,
        description: 'Balanced multi cap approach, 3Y CAGR: 15.2%',
        inceptionDate: new Date('2012-07-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SHRIRAM002',
        name: 'Shriram Flexi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 1.12,
        description: 'Opportunistic flexi cap investing, 5Y CAGR: 14.5%',
        inceptionDate: new Date('2014-04-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // More Sectoral/Thematic Funds
      {
        amfiCode: 'SBI008',
        name: 'SBI Infrastructure Fund',
        type: 'EQUITY',
        category: 'SECTORAL',
        benchmark: 'Nifty Infrastructure Index',
        expenseRatio: 1.45,
        description: 'Infrastructure sectoral fund, 5Y CAGR: 16.8%',
        inceptionDate: new Date('2005-01-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI009',
        name: 'ICICI Prudential Banking & PSU Debt Fund',
        type: 'EQUITY',
        category: 'SECTORAL',
        benchmark: 'Nifty Bank Index',
        expenseRatio: 1.28,
        description: 'Banking focused fund, 3Y CAGR: 14.5%',
        inceptionDate: new Date('2009-06-23'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANKLIN007',
        name: 'Franklin India Technology Fund',
        type: 'EQUITY',
        category: 'SECTORAL',
        benchmark: 'Nifty IT Index',
        expenseRatio: 1.35,
        description: 'IT sectoral fund, 5Y CAGR: 22.5%',
        inceptionDate: new Date('1998-12-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON005',
        name: 'Nippon India Power & Infra Fund',
        type: 'EQUITY',
        category: 'SECTORAL',
        benchmark: 'Nifty Infrastructure Index',
        expenseRatio: 1.42,
        description: 'Power and infrastructure theme, 3Y CAGR: 18.2%',
        inceptionDate: new Date('2004-08-23'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ADITYA003',
        name: 'Aditya Birla Sun Life Digital India Fund',
        type: 'EQUITY',
        category: 'THEMATIC',
        benchmark: 'Nifty 500',
        expenseRatio: 1.15,
        description: 'Digital and tech theme, 3Y CAGR: 21.8%',
        inceptionDate: new Date('2015-12-28'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HSBC004',
        name: 'HSBC Brazil Fund',
        type: 'EQUITY',
        category: 'THEMATIC',
        benchmark: 'MSCI Brazil Index',
        expenseRatio: 1.65,
        description: 'Brazil market exposure, 5Y CAGR: 8.5%',
        inceptionDate: new Date('2011-03-29'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MOTILAL003',
        name: 'Motilal Oswal Nifty 500 Fund',
        type: 'EQUITY',
        category: 'THEMATIC',
        benchmark: 'Nifty 500',
        expenseRatio: 0.35,
        description: 'Broad market index fund, 5Y CAGR: 14.2%',
        inceptionDate: new Date('2018-07-06'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // More Index Funds
      {
        amfiCode: 'SBI009',
        name: 'SBI Nifty Index Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.15,
        description: 'Low-cost Nifty 50 tracker, tracks index closely',
        inceptionDate: new Date('2010-05-03'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BANDHAN005',
        name: 'Bandhan Nifty 50 Index Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.18,
        description: 'Passive Nifty 50 investment, minimal tracking error',
        inceptionDate: new Date('2020-01-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'EDELWEISS005',
        name: 'Edelweiss ETF - Nifty 100',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.25,
        description: 'Nifty 100 ETF with tight tracking',
        inceptionDate: new Date('2019-12-11'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PRINCIPAL003',
        name: 'Principal Nifty 50 Equal Weight Index Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50 Equal Weight',
        expenseRatio: 0.32,
        description: 'Equal weight Nifty 50, 5Y CAGR: 13.8%',
        inceptionDate: new Date('2018-03-12'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // More ELSS Funds
      {
        amfiCode: 'BANDHAN006',
        name: 'Bandhan Tax Advantage (ELSS) Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'Nifty 500',
        expenseRatio: 0.82,
        description: 'Tax-saving ELSS with strong returns, 5Y CAGR: 16.5%',
        inceptionDate: new Date('2013-02-18'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PRINCIPAL004',
        name: 'Principal Tax Savings Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'Nifty 500',
        expenseRatio: 0.95,
        description: 'ELSS fund for 80C benefits, 5Y CAGR: 14.8%',
        inceptionDate: new Date('2009-02-02'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'L&T003',
        name: 'L&T Tax Advantage Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'BSE 200',
        expenseRatio: 0.88,
        description: 'Tax-saving fund with diversification, 10Y CAGR: 15.2%',
        inceptionDate: new Date('2007-01-16'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'EDELWEISS006',
        name: 'Edelweiss ELSS Tax Saver Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'Nifty 500',
        expenseRatio: 1.05,
        description: 'ELSS with growth focus, 3Y CAGR: 17.5%',
        inceptionDate: new Date('2009-12-29'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'UNION002',
        name: 'Union Long Term Equity Fund',
        type: 'EQUITY',
        category: 'ELSS',
        benchmark: 'Nifty 500',
        expenseRatio: 0.92,
        description: 'Tax-saving ELSS fund, 5Y CAGR: 15.8%',
        inceptionDate: new Date('2010-10-18'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // More International Funds
      {
        amfiCode: 'ADITYA004',
        name: 'Aditya Birla Sun Life International Equity Fund',
        type: 'EQUITY',
        category: 'INTERNATIONAL',
        benchmark: 'S&P 500',
        expenseRatio: 1.52,
        description: 'Global equity exposure, 5Y CAGR: 11.5%',
        inceptionDate: new Date('2010-12-23'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'EDELWEISS007',
        name: 'Edelweiss US Technology Equity FoF',
        type: 'EQUITY',
        category: 'INTERNATIONAL',
        benchmark: 'NASDAQ Technology Index',
        expenseRatio: 1.48,
        description: 'US tech sector exposure, 3Y CAGR: 16.8%',
        inceptionDate: new Date('2017-03-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PRINCIPAL005',
        name: 'Principal Global Opportunities Fund',
        type: 'EQUITY',
        category: 'INTERNATIONAL',
        benchmark: 'MSCI World Index',
        expenseRatio: 1.65,
        description: 'Global diversification, 5Y CAGR: 10.2%',
        inceptionDate: new Date('2012-05-14'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== MORE LARGE CAP FUNDS (15 Additional) ==========
      {
        amfiCode: 'PGIM002',
        name: 'PGIM India Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.72,
        description: 'Quality large cap fund, 5Y CAGR: 13.2%, strong portfolio',
        inceptionDate: new Date('2013-11-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SUNDARAM003',
        name: 'Sundaram Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.85,
        description: 'Bluechip focused fund, 3Y CAGR: 14.5%',
        inceptionDate: new Date('2012-06-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'QUANTUM002',
        name: 'Quantum Long Term Equity Value Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.64,
        description: 'Value investing large cap, 10Y CAGR: 12.8%',
        inceptionDate: new Date('2006-03-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'JM002',
        name: 'JM Core 11 Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.98,
        description: 'Concentrated large cap, 5Y CAGR: 13.8%',
        inceptionDate: new Date('2008-09-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MAHINDRA002',
        name: 'Mahindra Manulife Top 250 Nivesh Yojana',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.88,
        description: 'Top companies fund, 3Y CAGR: 14.2%',
        inceptionDate: new Date('2015-11-12'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'UNION003',
        name: 'Union Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.92,
        description: 'Diversified large cap, 5Y CAGR: 12.5%',
        inceptionDate: new Date('2014-08-25'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SHRIRAM003',
        name: 'Shriram Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.78,
        description: 'Quality bluechip fund, 3Y CAGR: 13.8%',
        inceptionDate: new Date('2016-02-18'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BOI002',
        name: 'BOI AXA Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.95,
        description: 'Large cap growth fund, 5Y CAGR: 12.8%',
        inceptionDate: new Date('2013-04-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'INVESCO003',
        name: 'Invesco India Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.82,
        description: 'Steady large cap returns, 10Y CAGR: 13.2%',
        inceptionDate: new Date('2008-03-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANK008',
        name: 'Franklin India Opportunities Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.88,
        description: 'Large cap opportunities, 5Y CAGR: 13.5%',
        inceptionDate: new Date('1999-01-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HDFC008',
        name: 'HDFC Index Fund - Nifty 50 Plan',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.2,
        description: 'Passive large cap fund, tracks Nifty 50',
        inceptionDate: new Date('2002-12-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI012',
        name: 'ICICI Prudential Dividend Yield Equity Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty Dividend Opportunities 50',
        expenseRatio: 0.92,
        description: 'Dividend-focused large cap, 5Y CAGR: 12.8%',
        inceptionDate: new Date('2007-11-21'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI012',
        name: 'SBI Focused Equity Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 50',
        expenseRatio: 0.68,
        description: 'Concentrated large cap portfolio, 10Y CAGR: 14.2%',
        inceptionDate: new Date('2004-03-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON008',
        name: 'Nippon India Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.75,
        description: 'Diversified large cap, 5Y CAGR: 13.2%',
        inceptionDate: new Date('2007-08-03'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'QUANT004',
        name: 'Quant Large Cap Fund',
        type: 'EQUITY',
        category: 'LARGE_CAP',
        benchmark: 'Nifty 100',
        expenseRatio: 0.62,
        description: 'Quantitative large cap strategy, 3Y CAGR: 15.5%',
        inceptionDate: new Date('2019-10-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== MORE MID CAP FUNDS (15 Additional) ==========
      {
        amfiCode: 'TATA004',
        name: 'Tata Mid Cap Growth Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.15,
        description: 'Growth-focused mid cap, 5Y CAGR: 19.2%',
        inceptionDate: new Date('2012-10-09'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON009',
        name: 'Nippon India Growth Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.05,
        description: 'Mid cap growth opportunities, 10Y CAGR: 18.5%',
        inceptionDate: new Date('1995-04-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI013',
        name: 'SBI Magnum Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.98,
        description: 'Established mid cap fund, 10Y CAGR: 17.8%',
        inceptionDate: new Date('2005-07-06'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'UTI005',
        name: 'UTI Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.08,
        description: 'Well-diversified mid cap, 5Y CAGR: 18.2%',
        inceptionDate: new Date('2004-03-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANK009',
        name: 'Franklin India Prima Plus Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.12,
        description: 'Mid cap value fund, 10Y CAGR: 17.5%',
        inceptionDate: new Date('1993-12-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ADITYA007',
        name: 'Aditya Birla Sun Life Pure Value Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.18,
        description: 'Value-oriented mid cap, 5Y CAGR: 19.5%',
        inceptionDate: new Date('2005-03-24'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'JM003',
        name: 'JM Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.25,
        description: 'Mid cap growth fund, 3Y CAGR: 21.2%',
        inceptionDate: new Date('2013-07-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'UNION004',
        name: 'Union Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.15,
        description: 'Dynamic mid cap investing, 5Y CAGR: 18.8%',
        inceptionDate: new Date('2014-06-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BOI003',
        name: 'BOI AXA Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.22,
        description: 'Mid cap opportunities, 3Y CAGR: 20.5%',
        inceptionDate: new Date('2015-03-12'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BARODA003',
        name: 'Baroda BNP Paribas Midcap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.18,
        description: 'Quality mid cap fund, 5Y CAGR: 17.8%',
        inceptionDate: new Date('2013-09-25'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'QUANTUM003',
        name: 'Quantum Equity Fund of Funds',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 0.95,
        description: 'Mid cap fund-of-funds, 3Y CAGR: 19.2%',
        inceptionDate: new Date('2016-10-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'IDFC003',
        name: 'IDFC Core Equity Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.08,
        description: 'Core mid cap portfolio, 5Y CAGR: 18.5%',
        inceptionDate: new Date('2011-08-02'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'LIC004',
        name: 'LIC MF Mid Cap Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.28,
        description: 'Mid cap growth strategy, 3Y CAGR: 19.8%',
        inceptionDate: new Date('2014-12-18'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PRINCIPAL006',
        name: 'Principal Emerging Bluechip Fund',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 150',
        expenseRatio: 1.15,
        description: 'Emerging leaders mid cap, 5Y CAGR: 18.2%',
        inceptionDate: new Date('2012-01-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'CANARA003',
        name: 'Canara Robeco Emerging Equities',
        type: 'EQUITY',
        category: 'MID_CAP',
        benchmark: 'Nifty Midcap 100',
        expenseRatio: 1.05,
        description: 'Mid cap emerging companies, 10Y CAGR: 17.5%',
        inceptionDate: new Date('2005-01-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== MORE SMALL CAP FUNDS (15 Additional) ==========
      {
        amfiCode: 'SUNDARAM004',
        name: 'Sundaram Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.42,
        description: 'High-growth small cap, 5Y CAGR: 25.5%',
        inceptionDate: new Date('2005-11-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PGIM003',
        name: 'PGIM India Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.35,
        description: 'Aggressive small cap growth, 3Y CAGR: 28.2%',
        inceptionDate: new Date('2015-07-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'INVESCO004',
        name: 'Invesco India Smallcap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.48,
        description: 'Small cap opportunities, 5Y CAGR: 24.8%',
        inceptionDate: new Date('2007-10-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'PRINCIPAL007',
        name: 'Principal Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.52,
        description: 'Future leaders small cap, 3Y CAGR: 27.5%',
        inceptionDate: new Date('2014-09-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'CANARA004',
        name: 'Canara Robeco Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.38,
        description: 'Small cap wealth creator, 5Y CAGR: 23.8%',
        inceptionDate: new Date('2010-09-13'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BOI004',
        name: 'BOI AXA Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.45,
        description: 'Small cap growth potential, 3Y CAGR: 26.8%',
        inceptionDate: new Date('2016-05-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SHRIRAM004',
        name: 'Shriram Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.55,
        description: 'Emerging businesses fund, 5Y CAGR: 22.5%',
        inceptionDate: new Date('2017-03-22'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'JM004',
        name: 'JM Small & Midcap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.48,
        description: 'Small cap focused fund, 3Y CAGR: 25.5%',
        inceptionDate: new Date('2015-11-30'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MAHINDRA003',
        name: 'Mahindra Manulife Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.42,
        description: 'Small cap alpha generator, 3Y CAGR: 27.2%',
        inceptionDate: new Date('2017-12-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'IDFC004',
        name: 'IDFC Emerging Businesses Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.38,
        description: 'Small cap disruptors fund, 5Y CAGR: 24.2%',
        inceptionDate: new Date('2013-10-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'BARODA004',
        name: 'Baroda BNP Paribas Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.45,
        description: 'Small cap value fund, 3Y CAGR: 26.5%',
        inceptionDate: new Date('2016-08-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'QUANTUM004',
        name: 'Quantum Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.28,
        description: 'Value-focused small cap, 5Y CAGR: 23.5%',
        inceptionDate: new Date('2018-01-10'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANK010',
        name: 'Franklin India Smaller Companies Fund II',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 1.35,
        description: 'Small cap growth fund, 10Y CAGR: 21.8%',
        inceptionDate: new Date('2008-06-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI013',
        name: 'ICICI Prudential Smallcap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 100',
        expenseRatio: 1.42,
        description: 'High conviction small cap, 5Y CAGR: 25.2%',
        inceptionDate: new Date('2009-10-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'MOTILAL005',
        name: 'Motilal Oswal Small Cap Fund',
        type: 'EQUITY',
        category: 'SMALL_CAP',
        benchmark: 'Nifty Smallcap 250',
        expenseRatio: 0.95,
        description: 'Research-driven small cap, 3Y CAGR: 29.5%',
        inceptionDate: new Date('2019-01-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ========== MORE MULTI CAP FUNDS (15 Additional) ==========
      {
        amfiCode: 'HDFC009',
        name: 'HDFC Equity Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.85,
        description: 'Diversified multi cap, 10Y CAGR: 15.8%',
        inceptionDate: new Date('1995-01-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ICICI014',
        name: 'ICICI Prudential Multicap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.92,
        description: 'Flexible multi cap allocation, 5Y CAGR: 16.2%',
        inceptionDate: new Date('1994-11-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SBI014',
        name: 'SBI Flexicap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.78,
        description: 'Dynamic flexi cap strategy, 10Y CAGR: 14.8%',
        inceptionDate: new Date('2004-11-16'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'NIPPON010',
        name: 'Nippon India Multi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.88,
        description: 'All-cap diversified fund, 10Y CAGR: 15.2%',
        inceptionDate: new Date('1995-09-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'AXIS011',
        name: 'Axis Multicap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.65,
        description: 'Low-cost multi cap fund, 5Y CAGR: 16.8%',
        inceptionDate: new Date('2019-11-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'FRANK011',
        name: 'Franklin India Equity Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.95,
        description: 'Multi cap opportunities, 10Y CAGR: 14.5%',
        inceptionDate: new Date('1999-03-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'TATA005',
        name: 'Tata Equity PE Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 1.05,
        description: 'Value multi cap fund, 5Y CAGR: 15.5%',
        inceptionDate: new Date('2004-05-28'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'DSP005',
        name: 'DSP Equity Opportunities Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.88,
        description: 'Flexible multi cap investing, 10Y CAGR: 15.8%',
        inceptionDate: new Date('1999-12-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'LIC005',
        name: 'LIC MF Multicap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 1.12,
        description: 'Diversified multi cap, 3Y CAGR: 16.5%',
        inceptionDate: new Date('2016-04-18'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'HSBC006',
        name: 'HSBC Flexi Cap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.92,
        description: 'All-market-cap exposure, 5Y CAGR: 15.2%',
        inceptionDate: new Date('2011-07-15'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'SUNDARAM005',
        name: 'Sundaram Diversified Equity Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.98,
        description: 'Multi cap diversification, 10Y CAGR: 14.2%',
        inceptionDate: new Date('2002-07-01'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'QUANTUM005',
        name: 'Quantum Dynamic Bond Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.85,
        description: 'Dynamic multi cap allocation, 3Y CAGR: 17.2%',
        inceptionDate: new Date('2017-09-20'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'UNION005',
        name: 'Union Multicap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 1.05,
        description: 'Flexible market cap strategy, 5Y CAGR: 14.8%',
        inceptionDate: new Date('2015-10-12'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'ADITYA008',
        name: 'Aditya Birla Sun Life Equity Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.88,
        description: 'Core multi cap portfolio, 10Y CAGR: 15.5%',
        inceptionDate: new Date('1995-03-31'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        amfiCode: 'INVESCO005',
        name: 'Invesco India Multicap Fund',
        type: 'EQUITY',
        category: 'MULTI_CAP',
        benchmark: 'Nifty 500',
        expenseRatio: 0.95,
        description: 'Opportunistic multi cap fund, 5Y CAGR: 16.2%',
        inceptionDate: new Date('2010-05-05'),
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    let fundCount = 0;
    for (const fund of funds) {
      const existingFund = await fundsCollection.findOne({
        amfiCode: fund.amfiCode,
      });

      if (!existingFund) {
        await fundsCollection.insertOne(fund);
        fundCount++;
        console.log(`✓ Created fund: ${fund.name}`);
      } else {
        console.log(`✓ Fund already exists: ${fund.name}`);
      }
    }

    // Add some sample NAV data for the first fund
    const firstFund = await fundsCollection.findOne({ amfiCode: 'HDFC001' });
    if (firstFund) {
      const performancesCollection = db.collection('fund_performances');
      const existingPerformances = await performancesCollection.countDocuments({
        fundId: firstFund._id,
      });

      if (existingPerformances === 0) {
        const navData = [];
        const today = new Date();
        for (let i = 30; i >= 0; i--) {
          const date = new Date(today);
          date.setDate(date.getDate() - i);
          navData.push({
            fundId: firstFund._id,
            date: date,
            nav: 45.32 + (Math.random() - 0.5) * 5,
            createdAt: new Date(),
          });
        }
        await performancesCollection.insertMany(navData);
        console.log(`✓ Added 31 days of NAV data for ${firstFund.name}`);
      }
    }

    // Add news articles
    const newsCollection = db.collection('news');
    const newsArticles = [
      {
        title: 'Mutual Funds See Record Inflows in October 2025',
        content:
          'Equity mutual funds witnessed their highest-ever monthly inflows of ₹40,608 crore in October 2025, reflecting strong investor confidence in the Indian stock market. Systematic Investment Plans (SIPs) contributed ₹23,547 crore to these inflows.',
        source: 'Economic Times',
        category: 'MARKET',
        tags: ['mutual funds', 'SIP', 'equity', 'inflows'],
        publishedAt: new Date('2025-11-06'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'SEBI Introduces New Guidelines for Mutual Fund Investments',
        content:
          'The Securities and Exchange Board of India (SEBI) has announced new guidelines aimed at enhancing transparency and investor protection in mutual fund investments. The changes include stricter disclosure norms and faster grievance redressal mechanisms.',
        source: 'Business Standard',
        category: 'REGULATION',
        tags: ['SEBI', 'regulations', 'investor protection'],
        publishedAt: new Date('2025-11-05'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Gold ETFs Gain Popularity Amid Market Volatility',
        content:
          'Gold Exchange Traded Funds (ETFs) have seen a surge in demand as investors seek safe-haven assets during recent market fluctuations. Gold prices touched ₹65,000 per 10 grams, driving interest in gold-backed investment instruments.',
        source: 'Mint',
        category: 'COMMODITIES',
        tags: ['gold', 'ETF', 'safe haven'],
        publishedAt: new Date('2025-11-04'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Tech Sector Funds Outperform Benchmark Indices',
        content:
          'Technology-focused mutual funds have delivered exceptional returns, outperforming major benchmark indices by 8-12% in the past quarter. Strong earnings from IT giants and optimistic global tech outlook fuel the rally.',
        source: 'Financial Express',
        category: 'SECTOR',
        tags: ['technology', 'performance', 'IT sector'],
        publishedAt: new Date('2025-11-03'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Small Cap Funds: High Returns Come with Higher Risks',
        content:
          'Financial advisors caution investors about the volatility in small-cap mutual funds despite their attractive returns. Experts recommend limiting exposure to 15-20% of the overall equity portfolio for risk management.',
        source: 'MoneyControl',
        category: 'ANALYSIS',
        tags: ['small cap', 'risk', 'portfolio'],
        publishedAt: new Date('2025-11-02'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Direct vs Regular Plans: Understanding the Cost Difference',
        content:
          'A comparative analysis reveals that direct mutual fund plans have saved investors up to 1.5% annually in expense ratios compared to regular plans. This difference can significantly impact long-term wealth creation.',
        source: 'Value Research',
        category: 'EDUCATION',
        tags: ['direct plans', 'expense ratio', 'cost'],
        publishedAt: new Date('2025-11-01'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'ESG Funds Attract Millennial Investors',
        content:
          'Environmental, Social, and Governance (ESG) focused mutual funds are witnessing growing interest from millennial investors who prioritize sustainable and responsible investing alongside financial returns.',
        source: 'Bloomberg Quint',
        category: 'TRENDS',
        tags: ['ESG', 'millennials', 'sustainable investing'],
        publishedAt: new Date('2025-10-31'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Debt Funds Face Pressure from Rising Interest Rates',
        content:
          'Debt mutual funds are experiencing outflows as the Reserve Bank of India maintains its hawkish stance on interest rates. Fund managers are repositioning portfolios to navigate the challenging fixed-income environment.',
        source: 'Economic Times',
        category: 'FIXED_INCOME',
        tags: ['debt funds', 'interest rates', 'RBI'],
        publishedAt: new Date('2025-10-30'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Tax-Saving ELSS Funds: Beat the March Rush',
        content:
          'Financial planners advise starting tax-saving investments in ELSS (Equity Linked Savings Scheme) funds early in the financial year to benefit from rupee cost averaging and avoid the year-end rush.',
        source: 'Mint',
        category: 'TAX',
        tags: ['ELSS', 'tax saving', '80C'],
        publishedAt: new Date('2025-10-29'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Index Funds vs Actively Managed Funds: The Ongoing Debate',
        content:
          'Recent data shows that over 60% of actively managed large-cap funds failed to beat their benchmark indices over a 5-year period, reigniting the debate about the merits of passive investing through index funds.',
        source: 'Business Standard',
        category: 'ANALYSIS',
        tags: ['index funds', 'active funds', 'performance'],
        publishedAt: new Date('2025-10-28'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'International Funds Offer Global Diversification',
        content:
          'International equity mutual funds are gaining traction as investors seek geographical diversification. Funds focused on US tech stocks and emerging markets have shown strong performance.',
        source: 'Financial Express',
        category: 'INTERNATIONAL',
        tags: ['international funds', 'diversification', 'global'],
        publishedAt: new Date('2025-10-27'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Mutual Fund AUM Crosses ₹50 Lakh Crore Milestone',
        content:
          'The Indian mutual fund industry has achieved a historic milestone with total Assets Under Management (AUM) crossing ₹50 lakh crore, driven by increasing retail participation and strong market performance.',
        source: 'MoneyControl',
        category: 'INDUSTRY',
        tags: ['AUM', 'milestone', 'growth'],
        publishedAt: new Date('2025-10-26'),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    let newsCount = 0;
    for (const article of newsArticles) {
      const existingNews = await newsCollection.findOne({
        title: article.title,
      });

      if (!existingNews) {
        await newsCollection.insertOne(article);
        newsCount++;
        console.log(`✓ Created news: ${article.title}`);
      } else {
        console.log(`✓ News already exists: ${article.title}`);
      }
    }

    console.log('\n🎉 Database seeded successfully!');
    console.log(
      `📊 Total: ${fundCount} new funds, ${funds.length - fundCount} existing`
    );
    console.log(
      `📰 News: ${newsCount} new articles, ${newsArticles.length - newsCount} existing`
    );
    console.log('\n📝 Test Credentials:');
    console.log('   Admin: admin@mutualfunds.com / admin123');
    console.log('   User:  test@example.com / test123');
  } catch (error) {
    console.error('Error seeding database:', error);
    throw error;
  } finally {
    await client.close();
    console.log('\n✓ Database connection closed');
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
